#pragma config(Motor,  port3,           liftLeftBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftLeftTop,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftRightBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRightTop,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           grabber,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[liftLeftBottom] = vexRT[Ch3];
		motor[liftLeftTop] = vexRT[Ch3];
		motor[liftRightBottom] = vexRT[Ch3];
		motor[liftRightTop] = vexRT[Ch3];
		
		motor[grabber] = vexRT[Ch2];
	}
}
