#pragma config(Motor,  port3,           liftLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           liftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           grabber,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int cubicMap(int x)
{
	return ((((x*3)/25)*((x*3)/25)*((x*3)/25)/27 + x/2)*2)/3;
}

task main()
{
	//	bool toggle = false;

	while(true) 
	{

		if(vexRT[Btn8U] == 1)
		{
			motor[liftLeft] = 15;
			motor[liftRight] = 15;
		}
		else if(vexRT[Btn5U] == 1)
		{
			motor[liftLeft] = cubicMap(vexRT[Ch3]);
			motor[liftRight] = cubicMap(vexRT[Ch3]);
		}
		else
		{
			motor[liftLeft] = vexRT[Ch3]/3;
			motor[liftRight] = vexRT[Ch3]/3;
		}

		motor[grabber] = cubicMap(vexRT[Ch2]);
	}

}
